spring.application.name=invoice
spring.data.mongodb.uri=mongodb+srv://mnagarajan1220:selvanaga123@smartbite.mua3xvo.mongodb.net/?retryWrites=true&w=majority&appName=Smartbite
spring.data.mongodb.database=invoicedb
